// Generated by CoffeeScript 1.7.1
if ($('body').length > 0) {
  $.stellar({
    horizontalScrolling: false,
    verticalScrolling: true,
    horizontalOffset: 0,
    verticalOffset: 0,
    responsive: true,
    scrollProperty: 'scroll',
    positionProperty: 'transform',
    parallaxBackgrounds: true,
    parallaxElements: false,
    hideDistantElements: true
  });
}
