// Generated by CoffeeScript 1.7.1
var body, button, scrollStop, viewport;

if ($('#scrollbtn').length > 0) {
  button = $('#scrollbtn');
  body = $('body');
  viewport = window.innerHeight;
  button.click(function() {
    body.animate({
      scrollTop: '+=' + viewport
    });
  });
  $(window).on("scroll", function() {
    var timer;
    clearTimeout(timer);
    return timer = setTimeout(scrollStop, 150);
  });
  scrollStop = function() {
    return console.log("scrolling stopped");
  };
}
