// Generated by CoffeeScript 1.6.3
var ScrollTo, scrollto;

ScrollTo = (function() {
  function ScrollTo() {}

  ScrollTo.prototype.vertical = function(target, speed) {
    if (speed == null) {
      speed = 300;
    }
    return $('html, body').animate({
      scrollTop: $(target).offset().top
    }, parseInt(speed));
  };

  return ScrollTo;

})();

scrollto = new ScrollTo;
