// Generated by CoffeeScript 1.7.1
var body, button, timeout, viewport;

if ($('#scrollbtn').length > 0) {
  button = $('#scrollbtn');
  body = $('body');
  timeout = null;
  viewport = window.innerHeight;
  button.click(function() {
    body.animate({
      scrollTop: '+=' + viewport
    });
  });
  $(window).bind("scroll", function() {
    clearTimeout(timeout);
    return timeout = setTimeout(function() {
      return button.fadeIn();
    }, 50);
  });
}
