// Generated by CoffeeScript 1.7.1
var body, button, timeout, viewport;

if ($('#scrollbtn').length > 0) {
  button = $('#scrollbtn');
  body = $('body');
  timeout = null;
  viewport = window.innerHeight;
  button.click(function() {
    body.animate({
      scrollTop: '+=' + viewport
    });
  });
  if (!$(window).scroll()) {
    alert("page scrolled");
  }
}
