// Generated by CoffeeScript 1.7.1
var link, submenu;

if ($('.menu').length > 0) {
  link = $('.menu-item-has-children a');
  submenu = $('.sub-menu');
  link.mouseenter(function() {
    return submenu.css("visibility", 'visible');
  });
  link.mouseleave(function() {
    return submenu.css("visibility", 'hidden');
  });
}
